### ISSUE TITLE
Lista de disciplinas desatualizada

### ISSUE THREAD

**Issue by schneiderfelipe** [matrufsc2/matrufsc2#10]
Olá,

Hoje as matrículas para a graduação foram abertas, mas não consigo encontrar praticamente nenhuma disciplina do curso de licenciatura em química, exceto Organizacao Escolar (EED5187).

Código de disciplinas que testei e não se encontram na lista:
- PSI5137;
- MEN5601;
- MEN7007;
- QMC5504;
- QMC5506;
- MEN7045;
- QMC5505;
- QMC5507;
- MEN7046;
- QMC5508;
- QMC5513;
- LSB7904;
- MEN7047;
- QMC5509;
- QMC5514.

Abraços,
Felipe

**Comment by fjorgemota** [comment]
Opa!

Esse problema já está para ser resolvido. É só um problema temporário que afeta o robô de vez em quando. Logo logo o problema deve estar restaurado.

Desculpe-nos pela inconveniência e obrigado pelo aviso, de qualquer forma. =)

Abs.

**Comment by fjorgemota** [comment]
Eu tinha fechado por se tratar de um problema temporário. Mas vou deixar a issue aberta até o robô realmente indexar os novos dados.

**Comment by schneiderfelipe** [comment]
Perfeito! Muito obrigado!
Aliás, parabéns pela ferramenta :1st_place_medal:

**Comment by fjorgemota** [comment]
Opa!

As disciplinas - até onde eu vi - foram finalmente indexadas, @dudektria. =)

Qualquer problema avise!

Abs.
