### ISSUE TITLE
Add 2019-2 data

### ISSUE THREAD

**Issue by munizart** [matrufsc2/matrufsc2#11]
Is it possible to add 2019-2 data?

**Comment by fjorgemota** [comment]
Hey. Thanks for opening the issue, but unfortunately I'm not maintaining the project anymore, as the crawler unfortunately stopped working with the Google's platform. 

Nonetheless ... I'm working on a new project (which will replace this one) that will be published yet this year. Hope to give more information about this soon. Meanwhile, I recommend you use https://matrufsc.caravela.club as an alternative in the meantime. :)

Thanks, again, for the contact, either way. :+1:

**Comment by munizart** [comment]
Thank you for your response and for that link, it was exactly what i was looking for.
Have a nice day :rocket:

**Comment by fjorgemota** [comment]
No problem. Thank you for creating the issue anyway. I'll close it now. Have a nice day you too! :)
